spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${gmail.username}
    password: ${gmail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

    mail:
      host: smtp.naver.com
      port: 465
      username: ${naver.username}
      password: ${naver.password}
      properties:
        mail:
          smtp:
            starttls:
              enable: true
            auth: true
            ssl:
              enable: true

#oauth:
#  kakao:
#    client-id: ${kakao.client-id}
#    url:
#      auth: https://kauth.kakao.com
#      api: https://kapi.kakao.com
#  naver:
#    secret: ${naver.client-secret}
#    client-id: ${naver.client-id}
#    url:
#      auth: https://nid.naver.com
#      api: https://openapi.naver.com

cloud:
  aws:
    region:
      static: ${aws.region}
    credentials:
      access-key: ${aws.access-key}
      secret-key: ${aws.secret-key}
    s3:
      bucket: ${aws.bucket}

jwt:
  secret: ${jwt.secret-key}

springdoc:
  packages-to-scan : greeny.backend
  swagger-ui :
    path : /api
  api-docs :
    path : /api-docs/json
    groups :
      enabled : true
  cache :
    disabled : true
  default-consumes-media-type : application/json;charset=UTF-8
  default-produces-media-type : application/json;charset=UTF-8